#Gives permission to install Salesforce CLI

sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

# The before_install steps downloads Salesforce CLI and installs it

before_install:
#Decrypt server key
- openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv
  -in assets/server.key.enc -out assets/server.key -d

#Assign variables
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG

#Create SFDX directory
- mkdir sfdx

#Install Salesforce CLI
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

#Authorizes Dev Hub
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a DevHub

jobs:
  include:
    - stage: test
      script:
        - echo 'content from test stage'
        - echo 'use for unit test' 
        #- sfdx force:org:create -v DevHub -s -f config/project-scratch-def.json -a ciorg
        #- sfdx force:org:display -u ciorg
        #- sfdx force:source:push -u ciorg
        #- sfdx force:apex:test:run -u ciorg --wait 10
        #- sfdx force:org:delete -u ciorg -p
    - stage: deploy
      script: 
        - echo 'content from deploy stage'
        - echo 'use for merge'
        #Creates package version
        #- PACKAGEVERSION="$(sfdx force:package:version:create --package $PACKAGENAME --installationkeybypass --wait 10 --json --targetdevhubusername HubOrg | jq '.result.SubscriberPackageVersionId' | tr -d '"')"
        #- echo "Package Version Id - "${PACKAGEVERSION}
        #- echo "Waiting for 5 minutes for package replication"
        #- sleep 5m
        #Creates scratch org
        #- sfdx force:org:create --targetdevhubusername DevHub --setdefaultusername --definitionfile config/project-scratch-def.json --setalias installorg --durationdays 1
        #Installs package in scratch org
        #- sfdx force:package:install --package $PACKAGEVERSION --wait 10 --targetusername DevHub
        #Runs unit tests on scratch org
        #- sfdx force:apex:test:run --targetusername DevHub --wait 10 --resultformat tap --codecoverage --testlevel $TESTLEVEL
        #Deletes scratch org
        #- sfdx force:org:delete --targetusername DevHub --noprompt

stages:
  - name: test
    if: type = push AND branch !=master
  #- name: 
    # require the type to be push to master
   # if: type = push AND branch = master
  - name: deploy
    # require the type to be a PR..
    if: type = pull_request
